### ISSUE TITLE
Is there a build guide or something for this device?

### ISSUE THREAD

**Issue by zhangmikoto** [LineageOS/android_device_xiaomi_natrium#1]
I went to the LineageOS's official wiki to find some guide for this device, and I found nothing. I cloned the device tree and the kernel source and tried to use "lunch" to build by myself, and I also had run the extractfiles.sh, but the terminal said like this:

build/core/product_config.mk:249: *** Can not locate config makefile for product "natrium". Stop.
build/core/product_config.mk:249: *** Can not locate config makefile for product "natrium" Stop.

** Don't have a product spec for: 'natrium'
** Do you have the right repo manifest?

So what should I do now?

**Comment by luca020400** [comment]
Building for natrium is unsupported as of now, you have to pick some changes from gerrit

**Comment by zhangmikoto** [comment]
Oh... Anyway, thanks a lot : )
